name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta diariamente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: AlanRiosMendoza
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate snake animation"
          add: "dist/*.svg"
